name: yt-downloader

services:
  server:
    container_name: yt-downloader
    build:
      dockerfile: Containerfile
      context: .
    volumes:
      - type: bind
        source: config.yaml
        target: /app/config.yaml
        read_only: true
      - type: bind
        source: cookies.txt
        target: /app/cookies.txt
        read_only: false
      - type: bind
        source: ~/Videos
        target: /app/downloads
        read_only: false
      - type: bind
        source: server.log
        target: /app/server.log
        read_only: false
    ports:
      - 9320:80
    restart: unless-stopped
